/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CRYPTO_System_APP;

import java.io.File;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Amine
 */
public class DescryptionPanel extends javax.swing.JPanel {
    private String selectedAlgorithm;
    private File selectedFile;

    /**
     * Creates new form DescryptionPanel
     */
    public DescryptionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        button_file_chooser = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        label_selected_file = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        cb_algo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        button_encrypt = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 10, true));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 10, true));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SWMono", 1, 65)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Decryption");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 570, 130));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 710, 190));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 10, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_file_chooser.setFont(new java.awt.Font("SWMono", 1, 18)); // NOI18N
        button_file_chooser.setText("Click here to select a File");
        button_file_chooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_file_chooserActionPerformed(evt);
            }
        });
        jPanel4.add(button_file_chooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 400, 30));

        jLabel4.setFont(new java.awt.Font("SWMono", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Select a File:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 140, 70));

        label_selected_file.setFont(new java.awt.Font("SWMono", 1, 18)); // NOI18N
        label_selected_file.setForeground(new java.awt.Color(255, 255, 255));
        label_selected_file.setText("No selected file ");
        jPanel4.add(label_selected_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 450, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 600, 100));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 10, true));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb_algo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choose the Algorithm...", "AES128", "AES256", "DES" }));
        cb_algo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_algoActionPerformed(evt);
            }
        });
        jPanel5.add(cb_algo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 230, 50));

        jLabel3.setFont(new java.awt.Font("SWMono", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select the Crypto-System :");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 360, 100));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 640, 90));

        jPanel6.setBackground(new java.awt.Color(0, 102, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_encrypt.setBackground(new java.awt.Color(0, 102, 0));
        button_encrypt.setFont(new java.awt.Font("SWMono", 1, 24)); // NOI18N
        button_encrypt.setForeground(new java.awt.Color(255, 255, 255));
        button_encrypt.setText("Decrypt File");
        button_encrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_encryptActionPerformed(evt);
            }
        });
        jPanel2.add(button_encrypt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 310, 60));

        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 410, 140));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 430, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_file_chooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_file_chooserActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        //fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));

        
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile();
            label_selected_file.setText(selectedFile.getName());
        }
    }//GEN-LAST:event_button_file_chooserActionPerformed

    private void cb_algoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_algoActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();
        selectedAlgorithm = (String)cb.getSelectedItem();
    }//GEN-LAST:event_cb_algoActionPerformed

    private void button_encryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_encryptActionPerformed
        // TODO add your handling code here:
        if (selectedFile != null && selectedAlgorithm != null) {
            try {
                FileEncryptor encryptor = new FileEncryptor();
                File outputFile = new File(selectedFile.getAbsolutePath().replace("."+selectedAlgorithm,"").replace(".enc", ""));

                encryptor.decrypt(selectedFile, outputFile, selectedAlgorithm);

                JOptionPane.showMessageDialog(null, "Le fichier a été décrypté avec succès!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Une erreur s'est produite lors du décryptage du fichier.");
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Veuillez sélectionner un fichier et un algorithme de décryptage.");
        }
    }//GEN-LAST:event_button_encryptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_encrypt;
    private javax.swing.JButton button_file_chooser;
    private javax.swing.JComboBox<String> cb_algo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel label_selected_file;
    // End of variables declaration//GEN-END:variables
}
